spring:
  application:
    name: reviewcoder

  datasource:
    url: jdbc:mysql://localhost:3306/reviewcoder?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: "a1346798"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate   #Flyway 사용
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false

  flyway:
    enabled: true
    baseline-on-migrate: true

  data:
    redis:
      host: localhost
      port: 6379

  mail:
    host: smtp.gmail.com
    port: 587
    username: ttl337123@gmail.com
    password: ynpu ljvn vgvy ynwe
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
aws:
  s3:
    bucket: your-bucket
    region: ap-northeast-2

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.authentication: DEBUG
    org.springframework.security.core.userdetails: TRACE